# Searching AGOL

## Overview

This notebook will look for any items (web maps, apps) and provide information on each item.

In brief, this notebook will:
1. Iterate over all web content in your org by [items/item type](https://developers.arcgis.com/rest/users-groups-and-items/items-and-item-types.htm)
    1. Iterate over all web maps in your org
    2. Iterate over all feature layers in your org
    3. Iterate over all web apps in your org
    4. Iterate over other items in org

2. Create a list of service ItemIDs
3. Create a list of service URLs

## Setup

#### Run this cell to connect to your GIS and get started:

In [1]:
from arcgis.gis import GIS
import pandas as pd
import os

gis = GIS("home")

## The Search

### Web Maps
First, we'll be getting a list of **all** the web maps in your org.

For each web map, it's as simple as using `get_data()` to return the JSON definition of the map as a string. We can then use `find` together with our service URL to see if it shows up.

Our `map_list` is created using **list comprehension** together with a **ternary operator**, which are very handy features for keeping your Python concise.

#### Searching outside your org
Add the parameter `outside_org=True` to the **search** to look for maps from *any* AGOL organization that are shared publicly. Obviously, that's going to be a LOT of information to look through, so only do that if you're certain you want to, then go get some coffee or something while it executes.

In [2]:
webmaps = gis.content.search('', item_type='Web Map', max_items=-1, outside_org=False)
#webmaps

In [3]:
len(webmaps)

290

In [4]:
map_list = [m for m in webmaps]
map_list

[<Item title:"Beta 2 - Commerce City Capital Improvement Projects" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Special Event Manager" type:Web Map owner:jmoening_c3>,
 <Item title:"Encampment Basemap" type:Web Map owner:rwoolf_c3>,
 <Item title:"Field Map with Parcels" type:Web Map owner:jmoening_c3>,
 <Item title:"Parks Data" type:Web Map owner:jallen_c3>,
 <Item title:"High Injury Network Locator" type:Web Map owner:jmoening_c3>,
 <Item title:"Situation Base Map" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"NS_Reports_D12" type:Web Map owner:jallen_c3>,
 <Item title:"projection issues" type:Web Map owner:jallen_c3>,
 <Item title:"Trails" type:Web Map owner:jallen_c3>,
 <Item title:"Irrigation Points" type:Web Map owner:jallen_c3>,
 <Item title:"test" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Zoning" type:Web Map owner:aperalta_c3>,
 <Item title:"Streets Repair & Maintenance_workers" type:Web Map owner:aperalta_c3>,
 <Item title:"CDOT Highways" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Pioneer Park" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Commerce City Facilities Map" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"CollectorSetUp" type:Web Map owner:mcampe_c3>,
 <Item title:"C3 Park Maintenance - Irrigation" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Points of Interest, Commerce City" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"NS_Reports_D10_Copy" type:Web Map owner:jallen_c3>,
 <Item title:"Irrigation Lines" type:Web Map owner:jallen_c3>,
 <Item title:"NS_Reports_D11D12" type:Web Map owner:jallen_c3>,
 <Item title:"StreetRepairs_FieldCollection_lines" type:Web Map owner:aperalta_c3>,
 <Item title:"SnowTrooperVersion3" type:Web Map owner:mcampe_c3>,
 <Item title:"PublicWorks StormWater Collector" type:Web Map owner:mcampe_c3>,
 <Item title:"NS_Reports_D8" type:Web Map owner:jallen_c3>,
 <Item title:"TreezyDifficult" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"PW Storm Inspections" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Enhanced Contrast Basemap" type:Web Map owner:jmoening_c3>,
 <Item title:"TEST COLL FC_ADDED" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Urban Trees (Learning Arcade)" type:Web Map owner:aolson_c3>,
 <Item title:"Population 18 years of age and older" type:Web Map owner:jmoening_c3>,
 <Item title:"2010 Annexation" type:Web Map owner:jmoening_c3>,
 <Item title:"CC Populations Density" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"DRCOG2022" type:Web Map owner:yuprety_c3>,
 <Item title:"External Property Lookup" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"2K CIP Project Basemap n Operational Layers" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Commerce City / Denver Metro Area" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Special Event Sanitation" type:Web Map owner:jmoening_c3>,
 <Item title:"Special Event Field Manager Dispatcher Map" type:Web Map owner:jmoening_c3>,
 <Item title:"Trash Request" type:Web Map owner:jmoening_c3>,
 <Item title:"Land Use" type:Web Map owner:jmoening_c3>,
 <Item title:"water_review_map" type:Web Map owner:mcampe_c3>,
 <Item title:"Duty Maintain Web Map" type:Web Map owner:rwoolf_c3>,
 <Item title:"Commerce City Capital Improvement Projects - newest-Copy" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Indonesian Forests_LC" type:Web Map owner:lcahill_c3>,
 <Item title:"CIPP Tracking Report Web Map" type:Web Map owner:aolson_c3>,
 <Item title:"Web map showing Priority Weed Road Corridor (fGDB)" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Hot Shot Clean Up Areas" type:Web Map owner:jallen_c3>,
 <Item title:"METRO DISTRICTS BASEMAP" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"CC Encampment Location" type:Web Map owner:rwoolf_c3>,
 <Item title:"Mowing Week 3" type:Web Map owner:aolson_c3>,
 <Item title:"Commerce City Historic Map" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Environmental Health " type:Web Map owner:jallen_c3>,
 <Item title:"FacilityData" type:Web Map owner:jallen_c3>,
 <Item title:"Special Events Traffic" type:Web Map owner:jmoening_c3>,
 <Item title:"Cleaning and Restocking Status Map" type:Web Map owner:jmoening_c3>,
 <Item title:"Special Event After Action" type:Web Map owner:jmoening_c3>,
 <Item title:"Electric charging stations in Canada" type:Web Map owner:jmoening_c3>,
 <Item title:"Planning Map" type:Web Map owner:jmoening_c3>,
 <Item title:"Hydrology" type:Web Map owner:jmoening_c3>,
 <Item title:"Forecasting Wildland Fire Recovery" type:Web Map owner:jmoening_c3>,
 <Item title:"Commerce City Boundary" type:Web Map owner:jmoening_c3>,
 <Item title:"Voting_Locations" type:Web Map owner:rwoolf_c3>,
 <Item title:"Encampment Outreach 2024" type:Web Map owner:jallen_c3>,
 <Item title:"High Injury Network Locator" type:Web Map owner:jmoening_c3>,
 <Item title:"Public Art" type:Web Map owner:rwoolf_c3>,
 <Item title:"Situation Base Map (Emergency Management)" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"CC Code Violation Map" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Parking Violations 2016-17 Heat Map" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Golf Course Irrigation Web Map - Edit FS (Sep 1)" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Planner Map" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Verizon GPS Data" type:Web Map owner:mcampe_c3>,
 <Item title:"CIP Operational Layers - Edit Data" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"USGS Geographic Name Service" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Eligible Marijuana Properties" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"CC_Tax_Entity_Basemap" type:Web Map owner:jmoening_c3>,
 <Item title:"PARKS" type:Web Map owner:jallen_c3>,
 <Item title:"Tree Inventory (old)" type:Web Map owner:mcampe_c3>,
 <Item title:"Irrigation Parks" type:Web Map owner:jallen_c3>,
 <Item title:"METRO DISTRICTS BASEMAP-JamieCopy" type:Web Map owner:jallen_c3>,
 <Item title:"Commerce City Ponds" type:Web Map owner:mcampe_c3>,
 <Item title:"SnowTrooperPlowedRoutes" type:Web Map owner:mcampe_c3>,
 <Item title:"MowingWebMap" type:Web Map owner:jallen_c3>,
 <Item title:"Treezy Peazy" type:Web Map owner:mcampe_c3>,
 <Item title:"CC Golf Course Map - Edit FS" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"NS_Reports_D4" type:Web Map owner:jallen_c3>,
 <Item title:"Four Core" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"CommerceCity_CartegraphBasemap_storm" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"NS_Reports_D3" type:Web Map owner:jallen_c3>,
 <Item title:"StreetRepair_FieldCollection_Points" type:Web Map owner:aperalta_c3>,
 <Item title:"NIGID Map" type:Web Map owner:etart_c3>,
 <Item title:"Stormwater Inlets Collector" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"MailingListForNS_Test" type:Web Map owner:mcampe_c3>,
 <Item title:"CityBaseMap_MSC" type:Web Map owner:mcampe_c3>,
 <Item title:"COPY_Ranger_Patrol_Field_Map_2" type:Web Map owner:rwoolf_c3>,
 <Item title:"test arcade nearest address" type:Web Map owner:aolson_c3>,
 <Item title:"PavementTreatmentCompleted2024" type:Web Map owner:jallen_c3>,
 <Item title:"Commerce City Capital Improvement Projects Basemap for Shortlist Map" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Commerce City Current Wards Population Target" type:Web Map owner:dgibson_c3>,
 <Item title:"Restricted Areas webmap" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Commerce City Public Art" type:Web Map owner:rwoolf_c3>,
 <Item title:"Story Map - Basemap for C3 Flood" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"TransMap Data 2023" type:Web Map owner:jallen_c3>,
 <Item title:"Basin Impact and Road Benefit Districts" type:Web Map owner:jallen_c3>,
 <Item title:"Special Event Field Manager" type:Web Map owner:jmoening_c3>,
 <Item title:"Special Event Operations Map" type:Web Map owner:jmoening_c3>,
 <Item title:"CC 2K Capital Projects (basemap as of Apr 14)" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"History of the City of Commerce City" type:Web Map owner:jallen_c3>,
 <Item title:"CC Retail Map" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Curbside Service Schedules" type:Web Map owner:jmoening_c3>,
 <Item title:"Active Development Under Review" type:Web Map owner:aolson_c3>,
 <Item title:"Zoning and Annexation" type:Web Map owner:jmoening_c3>,
 <Item title:"Encampment Status Pts" type:Web Map owner:rwoolf_c3>,
 <Item title:"Mowing Map" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Web Map- CC 2012 Aerial Imagery" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"CIP Web Map 2" type:Web Map owner:rwoolf_c3>,
 <Item title:"SO_Map_2021" type:Web Map owner:jallen_c3>,
 <Item title:"Schools" type:Web Map owner:jallen_c3>,
 <Item title:"Parks Irrigation Systems" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Parcel Violations 2016" type:Web Map owner:mcampe_c3>,
 <Item title:"NS_Reports_D7" type:Web Map owner:jallen_c3>,
 <Item title:"BMP Inspection" type:Web Map owner:mcampe_c3>,
 <Item title:"Culvert Inspection" type:Web Map owner:mcampe_c3>,
 <Item title:"AthleticAreas" type:Web Map owner:jallen_c3>,
 <Item title:"Zoning for Code (Field Map)" type:Web Map owner:jmoening_c3>,
 <Item title:"keeping years straight" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"CCPD Interactive Map" type:Web Map owner:mcampe_c3>,
 <Item title:"NS_Reports_D5" type:Web Map owner:jallen_c3>,
 <Item title:"Art" type:Web Map owner:rwoolf_c3>,
 <Item title:"Property Browser" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Commerce City Terrain Map" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"ParkFacilities" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"SubdivisionReviewTracking" type:Web Map owner:mcampe_c3>,
 <Item title:"Lines" type:Web Map owner:jallen_c3>,
 <Item title:"Special Event Form" type:Web Map owner:jmoening_c3>,
 <Item title:"Testing Recycling Arcade Functions" type:Web Map owner:aolson_c3>,
 <Item title:"Park Assets Field Map" type:Web Map owner:rwoolf_c3>,
 <Item title:"CC Trash and Recycling Map" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Vicinity Map" type:Web Map owner:mcampe_c3>,
 <Item title:"Test - Commerce City Capital Improvement Projects" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"PA Irrigation Map 2015" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Second Creek Community Park" type:Web Map owner:tferguson_c3>,
 <Item title:"Snow Removal Crosswalks" type:Web Map owner:mcampe_c3>,
 <Item title:"SnowPlow Map Test" type:Web Map owner:mcampe_c3>,
 <Item title:"NS_Reports_D1" type:Web Map owner:jallen_c3>,
 <Item title:"ParksProjectNEW" type:Web Map owner:mcampe_c3>,
 <Item title:"Open Space and Park Master" type:Web Map owner:jallen_c3>,
 <Item title:"Road concern reportting" type:Web Map owner:aperalta_c3>,
 <Item title:"Light_Structures_Parks" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Pavement Condition index" type:Web Map owner:aperalta_c3>,
 <Item title:"Zoning for Code (Map Service)" type:Web Map owner:rwoolf_c3>,
 <Item title:"PW Maintenance " type:Web Map owner:rwoolf_c3>,
 <Item title:"Ranger_Patrol_Field_Map" type:Web Map owner:rwoolf_c3>,
 <Item title:"ParkRanger_DailyActivity_Location" type:Web Map owner:jallen_c3>,
 <Item title:"Trash Request Manager" type:Web Map owner:jmoening_c3>,
 <Item title:"Parks and Trails Map" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Subdivision_Review_View" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Restaurants In Commerce City" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Commerce City Community Basemap" type:Web Map owner:jmoening_c3>,
 <Item title:"Liquor Map" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Map2" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Fatal and Serious Injury Dashboard" type:Web Map owner:jmoening_c3>,
 <Item title:"Fatal and Serious Injury Dashboard" type:Web Map owner:jmoening_c3>,
 <Item title:"Special Event Safety Resources" type:Web Map owner:jmoening_c3>,
 <Item title:"Traffic Counts C3" type:Web Map owner:ganderson_c3>,
 <Item title:"Encampment Field Map" type:Web Map owner:rwoolf_c3>,
 <Item title:"NIGID" type:Web Map owner:rwoolf_c3>,
 <Item title:"NS_Reports_D10" type:Web Map owner:jallen_c3>,
 <Item title:"Test Vector" type:Web Map owner:mcampe_c3>,
 <Item title:"Pioneer Park #2" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Utilisync_Sample" type:Web Map owner:jmoening_c3>,
 <Item title:"CC_Basemap_StormDRAPP" type:Web Map owner:jallen_c3>,
 <Item title:"SO_Restricted_Parcels_Map" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"NS_Reports_D6" type:Web Map owner:jallen_c3>,
 <Item title:"mc_basemap_test" type:Web Map owner:mcampe_c3>,
 <Item title:"test- Golf Course Irrigation Editing" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"FEMA's DG Imagery for Sept 2013 Flood" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Denver Amenities_MikeGarcia" type:Web Map owner:mcampe_c3>,
 <Item title:"NS- DEMO" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"2020 WARDS WEB MAP" type:Web Map owner:rwoolf_c3>,
 <Item title:"CC Trash Collection Map" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Encampment_Map" type:Web Map owner:jallen_c3>,
 <Item title:"_Cartegraph CC Basemap" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Parcel Finder Web Map-FS" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Capital Projects, 2K Basemap" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"2K CIP Project Basemap n Operational Layers-woCost" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Commerce City Capital Improvement Project Map" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Parcel Finder Web Map" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Trail and Open Space Field Map" type:Web Map owner:rwoolf_c3>,
 <Item title:"Ward City Council Map" type:Web Map owner:rwoolf_c3>,
 <Item title:"Commerce City Public Art Locations" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Cartegraph Streets" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Property Lookup Public" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Concrete Field Map Collection" type:Web Map owner:jallen_c3>,
 <Item title:"Park Review Map" type:Web Map owner:rwoolf_c3>,
 <Item title:"Commerce City Capital Improvement Projects - newest" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"CIP Web Map for App" type:Web Map owner:rwoolf_c3>,
 <Item title:"Active Development Under Construction" type:Web Map owner:aolson_c3>,
 <Item title:"Historical Subdivisions" type:Web Map owner:jmoening_c3>,
 <Item title:"Commerce City Boundary Map" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Updated Wards" type:Web Map owner:rwoolf_c3>,
 <Item title:"Property Browser 2018 External" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Public Works Reference Map" type:Web Map owner:jallen_c3>,
 <Item title:"Housing occupancy perctenage" type:Web Map owner:jmoening_c3>,
 <Item title:"2022 Annexations" type:Web Map owner:jmoening_c3>,
 <Item title:"Mowing Week 1" type:Web Map owner:aolson_c3>,
 <Item title:"Population Distribution 2020 Census" type:Web Map owner:jmoening_c3>,
 <Item title:"Commerce City and Enclaves" type:Web Map owner:jmoening_c3>,
 <Item title:"Marijuana License Application" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"East_Med" type:Web Map owner:tcrider_c3>,
 <Item title:"Mowing All Weeks" type:Web Map owner:aolson_c3>,
 <Item title:"StreetSweeping_FieldMap" type:Web Map owner:jallen_c3>,
 <Item title:"Nearmap Basemap" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Pothole19Krnl" type:Web Map owner:aperalta_c3>,
 <Item title:"Golf Course Feature Base Map w/Irrigation Base Map Features" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Tree Inventory_AugustBackup" type:Web Map owner:mcampe_c3>,
 <Item title:"CC Traffic Map" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"NS_Reports_D9" type:Web Map owner:jallen_c3>,
 <Item title:"CDOT Open GIS Layers" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Outfall Inspection" type:Web Map owner:mcampe_c3>,
 <Item title:"Golf Course Feature Base Map" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Cartegraph_Basemap_CC_TEST" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"METRO DISTRICTS Basemap" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"CC Map using Adams Co. Map Services" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Planning Map" type:Web Map owner:jallen_c3>,
 <Item title:"CC Parcel and Address WMS Map" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Citizen Problem Manager" type:Web Map owner:jallen_c3>,
 <Item title:"Special Event Site Map" type:Web Map owner:jmoening_c3>,
 <Item title:"Special Event Dispatcher Clear Assignments" type:Web Map owner:jmoening_c3>,
 <Item title:"Special Event Activity " type:Web Map owner:jmoening_c3>,
 <Item title:"Special Event Weather" type:Web Map owner:jmoening_c3>,
 <Item title:"Special Events Field Reporter" type:Web Map owner:jmoening_c3>,
 <Item title:"Parcel Finder Web Map_backup" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Parks and Trails for Interactive Use" type:Web Map owner:jmoening_c3>,
 <Item title:"CrackRepair" type:Web Map owner:jmoening_c3>,
 <Item title:"City Boundaries" type:Web Map owner:jmoening_c3>,
 <Item title:"Vicinity Map" type:Web Map owner:jmoening_c3>,
 <Item title:"Encampment Outreach 2023" type:Web Map owner:jallen_c3>,
 <Item title:"Parks" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"High Injury Network Locator" type:Web Map owner:rwoolf_c3>,
 <Item title:"Property Lookup InHouse" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Hyrdrography_NHD_Gauges" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"_Cartegraph Imagery Hybrid" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Fatal and Serious Injury Dashboard" type:Web Map owner:rwoolf_c3>,
 <Item title:"CC_Tax_Entity_Map" type:Web Map owner:jmoening_c3>,
 <Item title:"Commerce City Business Addresses" type:Web Map owner:jallen_c3>,
 <Item title:"Points_Parks" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"c3_Public_Art" type:Web Map owner:rwoolf_c3>,
 <Item title:"Adams_County_Elections_2" type:Web Map owner:rwoolf_c3>,
 <Item title:"City Oil and Gas Permits Web Map" type:Web Map owner:dmartinelli_c3>,
 <Item title:"_Cartegraph Community Map" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Census Map" type:Web Map owner:jmoening_c3>,
 <Item title:"CC_Basemap_Storm_External" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Parcel Finder Web Map Special Districts" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Community Map" type:Web Map owner:jmoening_c3>,
 <Item title:"TrashServices" type:Web Map owner:jallen_c3>,
 <Item title:"Mowing Week 2" type:Web Map owner:aolson_c3>,
 <Item title:"SnowTrooper" type:Web Map owner:mcampe_c3>,
 <Item title:"Northern Range Certificate of Occupancy 2010 - 2023" type:Web Map owner:rwoolf_c3>,
 <Item title:"UtiliSync Demo" type:Web Map owner:jallen_c3>,
 <Item title:"METRO DISTRICTS Base2020" type:Web Map owner:mcampe_c3>,
 <Item title:"Self Service Facilities" type:Web Map owner:jmoening_c3>,
 <Item title:"Traffic Count" type:Web Map owner:jmoening_c3>,
 <Item title:"Trails2016" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Map" type:Web Map owner:rwoolf_c3>,
 <Item title:"NHD - Selected" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Inlets" type:Web Map owner:mcampe_c3>,
 <Item title:"Collected_streetRepairs" type:Web Map owner:aperalta_c3>,
 <Item title:"SituationalAwareness" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"CC_ParkRangerDailyActivity" type:Web Map owner:jallen_c3>,
 <Item title:"Commerce City & USA Short-Term Weather Warnings" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Tree Inventory" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"Address_n_Sign_Verification" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"SnowTrooperVersion2" type:Web Map owner:mcampe_c3>,
 <Item title:"Subdivisions" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"City of Commerce City - SO Map" type:Web Map owner:C3_GIS_Admin>,
 <Item title:"NS_Reports_D6D7D8D9" type:Web Map owner:jallen_c3>,
 <Item title:"NS_Reports_D11" type:Web Map owner:jallen_c3>,

In [5]:
dependencies = pd.concat(
    [
        pd.DataFrame([{'title':m.title, 'id':m.id, 'type':m.type, 'url':f'{gis.url}/home/item.html?id={m.id}', 'owner':m.owner} for m in map_list])
    ]
)

dependencies.reset_index(inplace=True, drop=True)

dependencies.head()

,title,id,type,url,owner
0,Beta 2 - Commerce City Capital Improvement Pro...,79049db6dc6f43a2b8cf5f8b5266795c,Web Map,https://www.arcgis.com//home/item.html?id=7904...,C3_GIS_Admin
1,Special Event Manager,00fd8a29b9f94246b7901614cc731272,Web Map,https://www.arcgis.com//home/item.html?id=00fd...,jmoening_c3
2,Encampment Basemap,eee33cae6df7482498dbff14182a5302,Web Map,https://www.arcgis.com//home/item.html?id=eee3...,rwoolf_c3
3,Field Map with Parcels,dea32144c7144c0ebc19c95f4d22d3b2,Web Map,https://www.arcgis.com//home/item.html?id=dea3...,jmoening_c3
4,Parks Data,7dc3be295d274f878c26be9dc97f68d7,Web Map,https://www.arcgis.com//home/item.html?id=7dc3...,jallen_c3

### Feature Layers
Get a list of **all** the feature layers in your org.

In [6]:
lyr_list = gis.content.search('', item_type='Feature Layer', max_items=-1, outside_org=False)
lyr_list

[<Item title:"SpecialEventAssets" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Encampment Details Field Map App" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"2640" type:Feature Layer Collection owner:dmartinelli_c3>,
 <Item title:"test_AOIs" type:Feature Layer Collection owner:aolson_c3>,
 <Item title:"Commerce City Parcels" type:Feature Layer Collection owner:mcampe_c3>,
 <Item title:"c3_History" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"CC Encampment Location" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"Police Patrol Beat" type:Feature Layer Collection owner:mcampe_c3>,
 <Item title:"CommunityAddresses" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"Northfield and Quebec Layers" type:Feature Layer Collection owner:wnafziger_c3>,
 <Item title:"7255 Monaco Street Layers" type:Feature Layer Collection owner:wnafziger_c3>,
 <Item title:"LiqLicVendors" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"Parking Violations" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"City of Commerce City Public Works Warehouses" type:Feature Layer Collection owner:aperalta_c3>,
 <Item title:"Open Space And Park Master" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"Opportunity Zone 89.01 Layers" type:Feature Layer Collection owner:wnafziger_c3>,
 <Item title:"CCO Current Wards" type:Feature Layer Collection owner:dgibson_c3>,
 <Item title:"Commerce City Boundaries Provided by CCC GIS Layers" type:Feature Layer Collection owner:wnafziger_c3>,
 <Item title:"104th and Potomac Layers" type:Feature Layer Collection owner:wnafziger_c3>,
 <Item title:"E. 104th Ave. and Highway 2 Layers" type:Feature Layer Collection owner:wnafziger_c3>,
 <Item title:"Adams County Parcels" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"c3_City_Boundary" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"Zoning_Dissolve" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"TrafficCrashes" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"TrafficCrashes" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"CIP_02_Roads_pub" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"TrashServices_public" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"CIP_06_BasemapLines_pub" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"CC_SpecialDistricts" type:Feature Layer Collection owner:mcampe_c3>,
 <Item title:"StormWaterIntets_Only3" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"Light_Structures_Parks" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"ParksProjectNEW" type:Feature Layer Collection owner:mcampe_c3>,
 <Item title:"ParksProjectLayers" type:Feature Layer Collection owner:mcampe_c3>,
 <Item title:"Special Event Field Manager_fieldreports" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Crowd Areas CrowdCount_join" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Special Event Field Manager" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Health Points Status_currentjoin" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"HealthSafetyPlanning" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"WETLAND" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Annexations_JB" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"HistoricalSubdivisons" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Parks and Trails" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"PCI_Centerlines" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"Traffic Count Total1" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Crack Repair" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"PW_PavementManagement2024" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"Addresses" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"USA Census 2020 - Population Totals by Census Block" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"CIP_04_Rec_pub" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"Wards_buffer" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"City_Permits_Web_Map" type:Feature Layer Collection owner:dmartinelli_c3>,
 <Item title:"Duty Maintain Web Map_WFL1" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"GDB for CIPP Tracking Report" type:Feature Layer Collection owner:aolson_c3>,
 <Item title:"SpecialEvents" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Park Comments" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"C3GISR_SDE_RIVERS_STREAMS" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"C3GISR_SDE_FEMA_FLOOD_HAZARD" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"CityMask" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"Requests_public" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"OGP_MAP_gdb" type:Feature Layer Collection owner:dmartinelli_c3>,
 <Item title:"Lightrail Stations" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"USA Census 2020 - Age Demographics by Census Block" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Adams County Property Values" type:Table Layer owner:C3_GIS_Admin>,
 <Item title:"Golf Course Sprinkler FS - Value" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"Code Enforcement - Last Known Location" type:Feature Layer Collection owner:mcampe_c3>,
 <Item title:"Park_Points" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"Types_of_Issues" type:Feature Layer Collection owner:mcampe_c3>,
 <Item title:"CommerceCity_Restaurants_TEST" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"HighInjuryNetwork" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"EligibleMarijuanaParcels_dep" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"SO_Map_Restricted_Parcels" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"RestrictedAreas" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"StreetRepairs_FieldCollection_lines" type:Feature Layer Collection owner:aperalta_c3>,
 <Item title:"Walmart Brighton Layers" type:Feature Layer Collection owner:wnafziger_c3>,
 <Item title:"TreeAppInventory_2015_08_26" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"CollecterSetUp" type:Feature Layer Collection owner:mcampe_c3>,
 <Item title:"NS_Inspector_Zones" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"DriveCoded_centerLine" type:Feature Layer Collection owner:aperalta_c3>,
 <Item title:"CommerceCityRAWvanimg2018" type:Feature Layer Collection owner:aperalta_c3>,
 <Item title:"CommerceCityPavementCenterline" type:Feature Layer Collection owner:aperalta_c3>,
 <Item title:"Northern Range Retail Profile Layers" type:Feature Layer Collection owner:wnafziger_c3>,
 <Item title:"Tree_Condition" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"Northern Range E of E470 Layers" type:Feature Layer Collection owner:wnafziger_c3>,
 <Item title:"NS_Reports_2018" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"CC_ParkRangerDailyActivity" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"ParkRanger_DailyActivity_Location" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"Crash Data Points" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"Requests_submit" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Encampment_Outreach" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"MarijuanaLicense" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"pub_CityLimits_wEnclaves" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"CIP Web Map" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"New Wards 2023" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"Special Districts" type:Feature Layer Collection owner:mcampe_c3>,
 <Item title:"Patrol Violations" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"Commerce City Public Art Locations_WFL1" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"UtiliSyncDemo_gdb" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"Wards" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"FacilityData" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"CC_TaxEntities_v2_gdb_Hosted" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Center City Layers" type:Feature Layer Collection owner:bphetteplace_c3>,
 <Item title:"USA Census 2020 - Occupancy Totals by Census Block" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Commerce City Admin Layers" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"FourCore_TEST" type:Feature Layer Collection owner:aolson_c3>,
 <Item title:"Encampment Status Pts_WFL1" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"Trail or Open Space Asset Verifications" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"Mask" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"USA Census 2020 - Population Density by Census Block" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Streets" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"Annexation_2010" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"buffer_app" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"Line Polygon Data Verification" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"Trail Open Space GIS Data" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"C3_FloodPhotos_2013" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"SpecialEventRoutes_approved" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Health Points Status_join" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"CrackRepairCandidates24" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"City Parks Review" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"Parcels" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"C3_Addresses_FeatureService" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Trails" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"Map" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"1000" type:Feature Layer Collection owner:dmartinelli_c3>,
 <Item title:"Voting_Locations_WFL1" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"Annexation_2022" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"PriorityCorridors.gdb" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"EligibleMarijuanaParcel" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"COMMERCE CITY, CO METRO DISTRICTS" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"City Boundary" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"CDOT Parcels and ROW" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"Comments" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"USACensus2020Redistrict_Clip" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Northern COO Webmap" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"My Project Layers" type:Feature Layer Collection owner:nflock_c3>,
 <Item title:"Line" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"mph" type:Feature Layer Collection owner:mcampe_c3>,
 <Item title:"Irrigation Lines" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"SubdivisionReviewTracking_WFL1" type:Feature Layer Collection owner:mcampe_c3>,
 <Item title:"Subdivisions" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"Map_WFL1" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"NS_Reports_2019" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"Northern Range Layers" type:Feature Layer Collection owner:wnafziger_c3>,
 <Item title:"Subdivisions_SharePoint_1" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"Highway 2 and 96th Layers" type:Feature Layer Collection owner:wnafziger_c3>,
 <Item title:"Mowing_tfm" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"Points_of_Interest,_Commerce_City" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"StreetRepair_FieldCollection_Points" type:Feature Layer Collection owner:aperalta_c3>,
 <Item title:"CommerceCityCORegulatorySigns" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"Building Footprints" type:Feature Layer Collection owner:dmartinelli_c3>,
 <Item title:"Subdivisions_SharePoint" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"SpecialEventAssets_approved" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Historical Tracks Schema" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Inlet Inspection_stakeholder" type:Feature Layer Collection owner:mcampe_c3>,
 <Item title:"C3_PublicArt" type:Feature Layer Collection owner:mcampe_c3>,
 <Item title:"AdamsCounty_Elections" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"Requests" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Parks_Data" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"HighInjuryNetwork_public" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"HighInjuryNetwork" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"TrafficCrashes_public" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Traffic Counts" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"1320" type:Feature Layer Collection owner:dmartinelli_c3>,
 <Item title:"Police Patrol Beats" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"C3_Streets_PCI" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"Golf Course Sprinkler FS - Lateral Waterline" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"Stormwater_Inlets" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"Golf Course Sprinkler FS - Sprinkler" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"ParksProject" type:Feature Layer Collection owner:mcampe_c3>,
 <Item title:"Commerce City Layers" type:Feature Layer Collection owner:wnafziger_c3>,
 <Item title:"Park GIS Data" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"Park Asset Verification" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"CIP_03_Parks_pub" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"CrackRepair" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"CleanUpItems" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"CommerceCity_Restaurants" type:Table Layer owner:jallen_c3>,
 <Item title:"StormWaterIntets_Only_I" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"Test_JG" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"CC Encampment Location" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"Requests_trash" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"CIP_01Allpub" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"EncampmentOutreach2024" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"SpecialEventAssets_operations" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Special_Event_Field_Manager_type" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Tracking Schema" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"CrowdCount" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"CommercialAddresses_CC" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"Wards_buffer2" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"IGA Growth Boundary" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"Inlets" type:Feature Layer Collection owner:mcampe_c3>,
 <Item title:"Northern Range West of E 470 Layers" type:Feature Layer Collection owner:wnafziger_c3>,
 <Item title:"NS_Districts" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"Flatirons Mall Layers" type:Feature Layer Collection owner:wnafziger_c3>,
 <Item title:"Outfall Inspection" type:Feature Layer Collection owner:mcampe_c3>,
 <Item title:"TreeAppAncil_27" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"Commerce City Layers" type:Feature Layer Collection owner:bphetteplace_c3>,
 <Item title:"location_7bc8f5f06a7e47f68118e25afb37cb5a" type:Feature Layer Collection owner:aperalta_c3>,
 <Item title:"ProjectionIssues" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"Property Browser_stakeholder" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"Schools" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"Inlet Inspection" type:Feature Layer Collection owner:mcampe_c3>,
 <Item title:"BMP Inspection (Dec 2021)" type:Feature Layer Collection owner:mcampe_c3>,
 <Item title:"RTA Layers" type:Feature Layer Collection owner:wnafziger_c3>,
 <Item title:"September 2018 Criminal Trespass" type:Feature Layer Collection owner:nhougland_c3>,
 <Item title:"Commerce City Retail Leakage Layers" type:Feature Layer Collection owner:bphetteplace_c3>,
 <Item title:"HowSmartIsYourCommunity_Giesen" type:Feature Layer Collection owner:mcampe_c3>,
 <Item title:"Culvert Inspection" type:Feature Layer Collection owner:mcampe_c3>,
 <Item title:"Grid" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"Boarder_Clip" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Coral Reef Watch" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Annexation_2" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"Planning Map 2_WFL1" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"SafetyPlanning" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"TreeInventoryFromMaps" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"SignsParks" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"Golf Course Sprinkler FS - Controler" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"Golf Course Sprinkler FS - Irrigation Box" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"SO_MapUpdate_2021" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"Enclave Map Service" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"ImpactFeeMap" type:Feature Layer Collection owner:jallen_c3>,
 <Item title:"DRCOG_traffic_counts_2010_2023" type:Feature Layer Collection owner:jmoening_c3>,
 <Item title:"TrafficCrashes_public" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"Wards" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"2500" type:Feature Layer Collection owner:dmartinelli_c3>,
 <Item title:"King Soopers - 62nd Layers" type:Feature Layer Collection owner:wnafziger_c3>,
 <Item title:"Public Art" type:Feature Layer Collection owner:rwoolf_c3>,
 <Item title:"Northfield Shopping Center Layers" type:Feature Layer Collection owner:wnafziger_c3>,
 <Item title:"workers_7bc8f5f06a7e47f68118e25afb37cb5a" type:Feature Layer Collection owner:aperalta_c3>,
 <Item title:"City Limit" type:Feature Layer Collection owner:C3_GIS_Admin>,
 <Item title:"E. 104th Avenue and Chambers Road Layers" type:Feature Layer Collection owner:wnafziger_c3>,
 <Item title:"Prairie Center Layers" type:Feature Layer Collection owner:wnafziger_c3>,
 <Item title:"E. 104th Avenue and Highway 85 Layers" type:Feature Layer Collection owner:wnafziger_c3>,

### Web Apps
Now we'll be getting a list of **all** the web apps in your org. There are different `item_type`s for each, so we need to perform multiple queries and merge them together. Again, list comprehension makes this a nice short line, rather than nested for-loops.

In [7]:
apptypes = ['Application', 'Dashboard', 'Story Map', 'Web Experience']

app_list = [item for sublist in [gis.content.search('', item_type=t, max_items=-1, outside_org=False) for t in apptypes] for item in sublist]

In [8]:
app_list

[<Item title:"BA Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Void Analysis Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"City of Commerce City" type:Native Application owner:mcampe_c3>,
 <Item title:"Web App Builder" type:Web Mapping Application owner:bferguson_c3>,
 <Item title:"Parcel Finder Web Map" type:Web Mapping Application owner:C3_GIS_Admin>,
 <Item title:"NewPropertyLookup" type:Desktop Application Template owner:C3_GIS_Admin>,
 <Item title:"Northern Range West of E 470 Map Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Commerce City Boundaries Provided by CCC GIS Layers Filter Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Custom Symbols" type:Web Mapping Application owner:nflock_c3>,
 <Item title:"Commerce City Boundaries Provided by CCC GIS Layers Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Guided Tour Data" type:Web Mapping Application owner:bphetteplace_c3>,
 <Item title:"North Front Range Layers Filter Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Custom Icons" type:Web Mapping Application owner:bphetteplace_c3>,
 <Item title:"BA Web App Color Coded Maps Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Community Development Map Gallery" type:Web Mapping Application owner:C3_GIS_Admin>,
 <Item title:"Northern Range Map Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Northfield and Quebec Layers Filter Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Liquor License App" type:Web Mapping Application owner:C3_GIS_Admin>,
 <Item title:"BA Web App Void Analysis Data" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"MowingApp" type:Web Mapping Application owner:jallen_c3>,
 <Item title:"Geocortex User Preferences" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"Commerce City Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Neighborhood Services Reports" type:Web Mapping Application owner:jallen_c3>,
 <Item title:"Northern Range E of E470 Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Custom Color Picker Colors" type:Web Mapping Application owner:bphetteplace_c3>,
 <Item title:"60th and Vasquez Layers Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Custom Color Picker Colors" type:Web Mapping Application owner:nflock_c3>,
 <Item title:"Open Data" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"METRO DISTRICTS IL" type:Web Mapping Application owner:C3_GIS_Admin>,
 <Item title:"E. 104th Avenue and Highway 85 Layers Filter Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Highway 2 and 96th Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Highway 2 and 96th Map Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Variable Manager Data" type:Web Mapping Application owner:bphetteplace_c3>,
 <Item title:"BA Web App Comparison Reports Data" type:Web Mapping Application owner:nflock_c3>,
 <Item title:"BA Web App Smart Map Search Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"North Front Range Map Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Suitability Analysis Data" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"Commerce City Layers Preferences" type:Web Mapping Application owner:bphetteplace_c3>,
 <Item title:"Commerce City CIP Projects - Example App, Basic Viewer" type:Web Mapping Application owner:C3_GIS_Admin>,
 <Item title:"Flatirons Mall Layers Filter Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Commerce City Layers Filter Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Custom Color Ramps" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Core City Layers Filter Data" type:Web Mapping Application owner:bphetteplace_c3>,
 <Item title:"BA Web App Void Analysis Data" type:Web Mapping Application owner:nflock_c3>,
 <Item title:"Northern Range Layers Filter Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Favorite Reports Data" type:Web Mapping Application owner:bphetteplace_c3>,
 <Item title:"King Soopers - 62nd Layers Filter Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Custom Color Picker Colors" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Comparison Reports Variables" type:Web Mapping Application owner:bphetteplace_c3>,
 <Item title:"104th and Potomac Map Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"104th and Potomac Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Walmart Brighton Layers Filter Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Custom Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"E. 104th Ave. and Highway 2 Layers Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Center City Layers Preferences" type:Web Mapping Application owner:bphetteplace_c3>,
 <Item title:"Northfield and Quebec Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Highway 2 and 96th Layers Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"7255 Monaco Street Layers Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Special Event After Action" type:Web Mapping Application owner:jmoening_c3>,
 <Item title:"60th and Vasquez Layers Filter Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"PCI Tool" type:Web Mapping Application owner:aperalta_c3>,
 <Item title:"Orchard Town Center Layers Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Commerce City Layers Filter Data" type:Web Mapping Application owner:bphetteplace_c3>,
 <Item title:"E. 104th Avenue and Highway 85 Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Share Open dummy open data junk" type:Hub Site Application owner:C3_GIS_Admin>,
 <Item title:"City of Commerce City OpenData - Copied" type:Hub Site Application owner:mcampe_c3>,
 <Item title:"SnowPlow Web App Test" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"7255 Monaco Street Layers Filter Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Suitability Analysis Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Comparison Reports Variables" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Vicinity Web Map" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"NS_Reports_D8" type:Web Mapping Application owner:jallen_c3>,
 <Item title:"BA Web App Custom Symbols" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"NS Inspector Reports By District" type:Web Mapping Application owner:jallen_c3>,
 <Item title:"SO_Map_2021_WebApp" type:Web Mapping Application owner:jallen_c3>,
 <Item title:"BA Web App Void Analysis Data" type:Web Mapping Application owner:bphetteplace_c3>,
 <Item title:"My Project Map Data" type:Web Mapping Application owner:nflock_c3>,
 <Item title:"Light_Structures_Parks_Demo" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"Commerce City Retail Leakage Map Data" type:Web Mapping Application owner:bphetteplace_c3>,
 <Item title:"Sex Offenders Restricted Areas" type:Web Mapping Application owner:C3_GIS_Admin>,
 <Item title:"BA Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Commerce City Open Data" type:Hub Site Application owner:C3_GIS_Admin>,
 <Item title:"E. 104th Ave. and Highway 2 Map Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"E. 104th Avenue and Chambers Road Map Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Preferences" type:Web Mapping Application owner:bphetteplace_c3>,
 <Item title:"METRO DISTRICTS WAB" type:Web Mapping Application owner:C3_GIS_Admin>,
 <Item title:"Mike's WAB_DE on PC2312" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"Opportunity Zone 89.01 Layers Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Commerce City Boundaries Provided by CCC GIS Map Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Special Event Operations Apps" type:Web Mapping Application owner:jmoening_c3>,
 <Item title:"My Project Preferences" type:Web Mapping Application owner:nflock_c3>,
 <Item title:"BA Web App Custom Color Ramps" type:Web Mapping Application owner:nflock_c3>,
 <Item title:"BA Web App Site Suitability Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"CC_Test" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"MailingListForNeighborhoodServices" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"Oil and Gas Web Map" type:Web Mapping Application owner:dmartinelli_c3>,
 <Item title:"SnowTrooper" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"OilandGasWebMap" type:Web Mapping Application owner:C3_GIS_Admin>,
 <Item title:"E. 104th Ave. and Tower Road Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Favorite Reports Data" type:Web Mapping Application owner:nflock_c3>,
 <Item title:"CCPD Interactive Map" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"SubdivisionReviewTracking" type:Web Mapping Application owner:C3_GIS_Admin>,
 <Item title:"BA Web App Variable Manager Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Commerce City Open Data" type:Hub Site Application owner:jallen_c3>,
 <Item title:"E. 104th Avenue and Highway 85 Layers Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Migration Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Favorite Report Templates" type:Web Mapping Application owner:bphetteplace_c3>,
 <Item title:"Commerce City GIS" type:Hub Site Application owner:mcampe_c3>,
 <Item title:"Historic Places in the City of Commerce City" type:Web Mapping Application owner:C3_GIS_Admin>,
 <Item title:"Traffic Count" type:Web Mapping Application owner:jbrennan_c3>,
 <Item title:"Test Tax Entity Lookup" type:Web Mapping Application owner:jmoening_c3>,
 <Item title:"BA Web App Custom Symbols" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"Commerce City Retail Leakage Layers Preferences" type:Web Mapping Application owner:bphetteplace_c3>,
 <Item title:"BA Web App Smart Map Search Data" type:Web Mapping Application owner:bphetteplace_c3>,
 <Item title:"VerifyPermitAddress" type:Web Mapping Application owner:C3_GIS_Admin>,
 <Item title:"Opportunity Zone 89.01 Layers Filter Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"King Soopers - 62nd Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Preferences" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"Web app showing Priority Weed Road Corridor (fGDB)" type:Web Mapping Application owner:C3_GIS_Admin>,
 <Item title:"Favorite Report Templates" type:Web Mapping Application owner:nflock_c3>,
 <Item title:"BA Web App New Comparison Reports Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Old Template Editor Report Themes Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"City of Commerce City Special Districts Map" type:Web Mapping Application owner:C3_GIS_Admin>,
 <Item title:"BA Preferences" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"Core City Map Data" type:Web Mapping Application owner:bphetteplace_c3>,
 <Item title:"Commerce City CIP Project Web App - Example Simple Viewer" type:Web Mapping Application owner:C3_GIS_Admin>,
 <Item title:"King Soopers - 62nd Layers Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"RTA Layers Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"PARKS" type:Web Mapping Application owner:jallen_c3>,
 <Item title:"Parks In Commerce City" type:Web Mapping Application owner:jallen_c3>,
 <Item title:"Flatirons Mall Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Custom Icons" type:Web Mapping Application owner:nflock_c3>,
 <Item title:"Special Event Operations Map" type:Web Mapping Application owner:jmoening_c3>,
 <Item title:"Orchard Town Center Map Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Updated City Coucil Wards" type:Web Mapping Application owner:C3_GIS_Admin>,
 <Item title:"In House Property Lookup" type:Web Mapping Application owner:C3_GIS_Admin>,
 <Item title:"Snow Removal Crosswalks" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"Edit CIP Operational Layers" type:Web Mapping Application owner:C3_GIS_Admin>,
 <Item title:"BA Web App Color Coded Maps Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"E. 104th Avenue and Chambers Road Layers Filter Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Commerce City Water Review Map" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"Northern Range E of E470 Map Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Guided Tour Data" type:Web Mapping Application owner:nflock_c3>,
 <Item title:"King Soopers Marketplace Layers Filter Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Guided Tour Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Senior Living Layers Preferences" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"BA Web App Custom Color Ramps" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Address Data Management" type:Desktop Application Template owner:C3_GIS_Admin>,
 <Item title:"Brighton Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Property Lookup" type:Web Mapping Application owner:C3_GIS_Admin>,
 <Item title:"Liquor and Marijuana Licenses" type:Web Mapping Application owner:C3_GIS_Admin>,
 <Item title:"Commerce City Map Data" type:Web Mapping Application owner:bphetteplace_c3>,
 <Item title:"BA Web App Template Editor Report Themes Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Favorite Reports Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Art Draft 1" type:Web Mapping Application owner:rwoolf_c3>,
 <Item title:"BA Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"E. 104th Avenue and Highway 85 Map Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Special Event Site Map " type:Web Mapping Application owner:jmoening_c3>,
 <Item title:"Commerce City CIP Project Application (Story Map Basic)" type:Web Mapping Application owner:C3_GIS_Admin>,
 <Item title:"Northfield and Quebec Layers Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Highway 2 and 96th Layers Filter Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Commerce City Public Art Story Map" type:Web Mapping Application owner:rwoolf_c3>,
 <Item title:"North Front Range Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"My Project Layers Filter Data" type:Web Mapping Application owner:nflock_c3>,
 <Item title:"Core City Preferences" type:Web Mapping Application owner:bphetteplace_c3>,
 <Item title:"Citizen Problem Manager" type:Web Mapping Application owner:jallen_c3>,
 <Item title:"E. 104th Avenue and Chambers Road Layers Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"King Soopers Marketplace Map Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"King Soopers Marketplace Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"104th and Potomac Layers Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"mc_test" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"mc_test2" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"BA Web App Statistical Data Collections Data" type:Web Mapping Application owner:bphetteplace_c3>,
 <Item title:"King Soopers Marketplace Layers Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"104th and Potomac Layers Filter Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Commerce City Map Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Draft_Art_2" type:Web Mapping Application owner:rwoolf_c3>,
 <Item title:"test" type:Web Mapping Application owner:jallen_c3>,
 <Item title:"Northern Range E of E470 Layers Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Verizon GPS Data" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"BA Web App Template Editor Report Themes Data" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"BA Web App Statistical Data Collections Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"60th and Vasquez Map Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Variable Manager Data" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"Walmart Brighton Layers Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"TransMap 2023 Data" type:Web Mapping Application owner:jallen_c3>,
 <Item title:"E. 104th Ave. and Highway 2 Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Comparison Reports Data" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"BA Preferences" type:Web Mapping Application owner:nflock_c3>,
 <Item title:"RTA Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Custom Symbols" type:Web Mapping Application owner:bphetteplace_c3>,
 <Item title:"Favorite Report Templates" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Migration Data" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"BA Web App Guided Tour Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Favorite Reports Data" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"7255 Monaco Street Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Web App Builder JTJ" type:Web Mapping Application owner:bferguson_c3>,
 <Item title:"Duty to Maintain Web Map" type:Web Mapping Application owner:rwoolf_c3>,
 <Item title:"CC Capital Improvement Projects - Example Web App, Story Map Tabbed" type:Web Mapping Application owner:C3_GIS_Admin>,
 <Item title:"Prairie Center Layers Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"BA Web App Custom Color Ramps" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"E. 104th Ave. and Tower Road Layers Preferences" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Senior Living Layers Filter Data" type:Web Mapping Application owner:mcampe_c3>,
 <Item title:"Printable Area Map Template" type:Web Mapping Application owner:C3_GIS_Admin>,
 <Item title:"Northfield Shopping Center Layers Filter Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"C3GISENT Web AppBuilder" type:Application owner:C3_GIS_Admin>,
 <Item title:"BA Web App Void Analysis Data" type:Web Mapping Application owner:wnafziger_c3>,
 <Item title:"Zoning and Annexation" type:Web Mapping Application owner:jbrennan_c3>,
 <Item title:"New Property Browser" type:Web Mapping Application owner:C3_GIS_Admin>,

### Other Items in Org
Get a list of different types of items in the org site.

In [9]:
item = gis.content.search('', item_type='Map Files', max_items=-1, outside_org=False)
item

[]

In [10]:
item = gis.content.search('', item_type='Tile Layer', max_items=-1, outside_org=False)
item

[]

## Reviewing the Output

Now we've got our lists of maps and apps. But to get them in a user-friendly format, we'll use `pandas` to cobble together a dataframe.

In [29]:
orgData = pd.concat(
    [
        pd.DataFrame([{'title':a.title, 'id':a.id, 'type':a.type, 'url':f'{gis.url}/home/item.html?id={a.id}', 'owner':a.owner} for a in app_list]),
        pd.DataFrame([{'title':m.title, 'id':m.id, 'type':m.type, 'url':f'{gis.url}/home/item.html?id={m.id}', 'owner':m.owner} for m in map_list]),
        pd.DataFrame([{'title':l.title, 'id':l.id, 'type':l.type, 'url':f'{gis.url}/home/item.html?id={l.id}', 'owner':l.owner} for l in lyr_list])
    ]
)

orgData.reset_index(inplace=True, drop=True)

orgData.head()

,title,id,type,url,owner
0,CIP Web App,2fd3018832744b9b910f81aca244da90,Web Mapping Application,https://www.arcgis.com//home/item.html?id=2fd3...,rwoolf_c3
1,Parcel Finder Web Map,9a0bd457466848e18f59fb5538ffc558,Web Mapping Application,https://www.arcgis.com//home/item.html?id=9a0b...,C3_GIS_Admin
2,City of Commerce City,e7db9af47c354712ac622a1cd1446310,Native Application,https://www.arcgis.com//home/item.html?id=e7db...,mcampe_c3
3,Web App Builder C3GIS,a1cc9b850fa249068eb2b7ef7a192ffa,Web Mapping Application,https://www.arcgis.com//home/item.html?id=a1cc...,C3_GIS_Admin
4,Web App Builder,196bd94d9bf0486ebd76aee58ac1b997,Web Mapping Application,https://www.arcgis.com//home/item.html?id=196b...,bferguson_c3

In [34]:
idList = orgData['id']

In [35]:
len(idList)

880

## Export CSV

Now you've got your output, but what do you do with it? Well, you could use `dependencies.to_csv()` to save the dataframe to a file.
If you're just tracking down references to your service to replace or remove them, you can use the `url` column to go straight to the item's page in your portal and make the necessary adjustments.

In [30]:
csv = r'C:\Users\is_olson\Documents\Projects\ArcGIS-for-Server\DependencySearch\test.csv'
myCSV = orgData.to_csv(csv)